#version: '3.8'
#
#services:
#  postgres:
#    image: postgres:latest
#    environment:
#      POSTGRES_DB: qrcode
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 1234
#    ports:
#      - "5433:5432"
#    networks:
#      - app-network
#
#  app:
#    image: qrcode-k8s:v3
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8090:8090"
#    environment:
#      DB_HOST: postgres
#      DB_NAME: qrcode
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 1234
#    depends_on:
#      - postgres
#    networks:
#      - app-network
#
#networks:
#  app-network:
#    driver: bridge